config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: "registrations" }

  resources :movies, only: [:new, :index, :show, :create] do
    resources :reviews, only: [:index, :create, :new]
  end
  resources :users, only: :show, path: 'profile' do
    resources :reviews, only: [:index]
    resources :watchlists, only: [:index]
    member do
      get :follow
      get :unfollow
      get :followers
      get :following
    end
  end

  resources :reviews, except: [:new, :index]
  resources :tags, only: [:show]
  resources :watchlists, only: [:create, :update, :index]

  get '/search', to: 'movies#new'
  get '/dashboard', to: 'users#dashboard'

  root 'welcome#index'
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def show
    @movie = Movie.find_by(id: params[:id])
  end

  def new
  end

  def create
    find_or_create_movie params[:imdbid] if params[:imdbid]
  end

end

app/helpers/movies_helper.rb
module MoviesHelper

end

app/views/movies/_search_form.html.erb
<%= form_tag movies_path, method: :get do %>
  <%= text_field_tag('search', nil, placeholder: 'search for a movie') %>

  <%= button_tag type: 'submit', class: "button" do %>
    <%= fa_icon "search" %>
  <% end %>
<% end %>

app/views/movies/_watchlist_form.html.erb
<% if current_user.watchlist && !current_user.watchlist.movies.include?(@movie) || current_user.watchlist.nil? %>

  <%= form_with model: @watchlist, url: watchlists_path do |f| %>
    <%= f.hidden_field :movie_id, value: @movie.id %>

    <%= button_tag :submit , class: "button data-button" do %>
      <i class="fas fa-eye"></i>
    <% end %>
  <% end %>

<% elsif current_user.watchlist %>

<%= form_with model: @watchlist, url: watchlist_path(current_user.watchlist), method: :patch do |f| %>
  <%= f.hidden_field :movie_id, value: @movie.id %>
  <%= f.hidden_field :watchlist_id, value: current_user.watchlist.id %>

  <%= button_tag :submit , class: "button delete-button" do %>
    <i class="fas fa-eye-slash"></i>
  <% end %>
<% end %>

<% end %>

app/views/movies/show.html.erb
<section class="row">
  <section class="column col-left">
    <div class="movie-data">
    <%= render partial: 'movie_data', locals: {movie: @movie} %>
    <br>
    <div class="row">
      <%= button_to new_movie_review_path(@movie), method: :get, class: "button success-button" do %>
        <i class="fas fa-pen-square"></i>
      <% end %>

      <%= render 'watchlist_form' %>
      <%= render "home_button" %>
    </div>
    </div>
  </section>

  <% if @movie.reviews.present? %>
  <section class="column dash-review-container">
    <h3>reviews:</h3><br>
    <% @movie.reviews.each do |review| %>
    <div class="review">
      <%= link_to review_path(review) do %>
        <span class="more-button"><i class="fas fa-ellipsis-h"></i></span>
      <% end %>
      <span><%= link_to review.user.username, user_path(review.user), class: "username" %></span><br>
      <%= review.render_content %>
    </div>
    <% end %>
  </section>
  <% end %>

</section>