config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: "registrations" }

  resources :movies, only: [:new, :index, :show, :create] do
    resources :reviews, only: [:index, :create, :new]
  end
  resources :users, only: :show, path: 'profile' do
    resources :reviews, only: [:index]
    resources :watchlists, only: [:index]
    member do
      get :follow
      get :unfollow
      get :followers
      get :following
    end
  end

  resources :reviews, except: [:new, :index]
  resources :tags, only: [:show]
  resources :watchlists, only: [:create, :update, :index]

  get '/search', to: 'movies#new'
  get '/dashboard', to: 'users#dashboard'

  root 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,
         :omniauthable, omniauth_providers: %i[github], authentication_keys: %i[username]

  has_many :reviews, dependent: :destroy
  has_many :movies, through: :reviews
  belongs_to :watchlist, optional: true 

  validates :username, uniqueness: true
  validates :username, presence: true
  validates :password, presence: true, on: :create
  validates :password, length: {in: 6..24}, on: :create
  validates :bio, length: {maximum: 500}
  validates :tagline, length: {maximum: 30}

  acts_as_follower
  acts_as_followable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.username = auth.info.nickname
    user.password = Devise.friendly_token[0, 20]
    end
  end

  def self.recent_movies
    joins(:movies).sort_by{|t| - t.created_at.to_i}.first(5)
  end

  def render_bio
    self.bio.gsub("\r\n\r", '<br>').gsub("\r\n", '<br>').gsub("\n", '<br>').html_safe
  end

  def new_from_following
    self.all_following.map do |friend|
      friend_movies = []
      friend_movies << friend.movies.map {|movie| movie}.sort_by {|m| m.created_at}
    end.reject { |e| e.empty?}.flatten.uniq
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, kind: "github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController

  def show
  end

  def dashboard
    @movie = Movie.new
    if params[:search]
      @movie_list = []
      movie = params[:search]
      query = search_api(movie)
      if !query['Search'].nil?
        @movie_list = query['Search'].compact.map do |m|
          if m['Poster']== 'N/A'
            m['Poster'] = 'https://66.media.tumblr.com/5a186c216ce45dbc68730be8ced57a06/e872194058456955-3c/s400x600/68cd75aef527634109c5573a4ef945941dc451b2.png'
          end
          Movie.new(title: m['Title'], year: m['Year'], poster: m['Poster'], imdbid: m['imdbID'])
        end
      else
        flash[:notice] = "No results bro"
      end
    end
    render :dashboard
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_follows

  def show
    @movies = Movie.user_movies(@user)
  end

  def dashboard
    @popular = Movie.popular_this_week
  end


  def follow
    if @user == current_user
      flash[:alert] = "you're great and all but you can't follow yourself"
    elsif @user.followed_by?(current_user)
      flash[:alert] = "you're already following #{@user.username}"
    else
      current_user.follow(@user)
      flash[:notice] = "now following #{@user.username}"
    end
    redirect_to user_path(@user)
  end

  def unfollow
    current_user.stop_following(@user)
    redirect_to user_path(@user), alert: "unfollowed #{@user.username}"
  end

  def followers
  end

  def following
  end


  private

  def set_user
    if params[:id]
      @user = User.find(params[:id])
    else
      @user = current_user
    end
  end

  def set_follows
    @following = @user.all_following
    @followers = @user.followers
  end

end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/user_helper.rb
module Users::UserHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def all_follow_reviews(follows, num)
    follows.map do |user|
      user.reviews
    end.flatten.sample(num)
  end

  def mutuals?(user)
    user.following?(current_user) && user.followed_by?(current_user)
  end

end

app/views/users/_follow_button.html.erb
  <% if @user != current_user %>
    <% if @user.followed_by?(current_user) %>
      <%= button_to unfollow_user_path(@user), method: :get, class: "button delete-button follow-button" do %>
        <%= fa_icon "times" %>
        <span>unfollow <%= @user.username %></span>
      <% end %>
    <% else %>
      <%= button_to follow_user_path(@user), method: :get, class: "button success-button follow-button" do %>
        <%= fa_icon "plus" %>
        <span>follow <%= @user.username %></span>
      <% end %>
    <% end %>
  <% end %>

app/views/users/_followers.html.erb
<% if @user == current_user %>
<h2>people who follow you.</h2>
<% else %>
<h2>people following <%=@user.username%>.</h2>
<% end %>
<div class="follow-container">
  <% @followers.each do |user| %>
  <div class="user-card">
    <%= link_to user.username, user_path(user), class: "username" %><br>
    <% if user.tagline %>
    <p class="tagline"><%= user.tagline %></p>
    <% end %>
  </div>
  <% end %>
</div>

app/views/users/_following.html.erb
<% if @user == current_user %>
<h2>people you follow.</h2>
<% else %>
<h2>people <%=@user.username%> follows.</h2>
<% end %>
<div class="follow-container">
  <% @following.each do |user| %>
  <div class="user-card">
    <%= link_to user.username, user_path(user), class: "username" %><br>
    <% if user.tagline %>
    <p class="tagline"><%= user.tagline %></p>
    <% end %>
  </div>
  <% end %>
</div>

app/views/users/_follows.html.erb
<% if @user == current_user %>
<h2>people you follow.</h2>
<% else %>
<h2>people <%=@user.username%> follows.</h2>
<% end %>
<div class="follow-container">
  <% @follows.each do |user| %>
  <div class="user-card">
    <%= link_to user.username, user_path(user), class: "username" %><br>
    <% if user.tagline %>
    <p class="tagline"><%= user.tagline %></p>
    <% end %>
  </div>
  <% end %>
</div>

app/views/users/_profile_info.html.erb
<div class="profile-info">
<h1 class="username"> <%= @user.username %></h1>

<% if mutuals?(@user) %>
  <span class="mutuals-flag"><i class="fas fa-star"></i></span>
<% elsif @user.following? current_user %>
  <span class="follow-flag"><i class="fas fa-check-square"></i></span>
<% end %>
<%= link_to "followers: #{@user.followers_count}", followers_user_path, class: "button" %>
<%= link_to "following: #{@user.follow_count}", following_user_path, class: "button" %>

<br><br>
<% if @user.tagline %>
  <p class="tagline"><%= @user.tagline %></p><br><br>
<% end %>

<% if @user.reviews %>
  <%= link_to user_reviews_path(@user), class: "button" do %>
    <i class="fas fa-pen-square"></i>
    <span><%= pluralize(@user.reviews.count, 'review') %></span>
  <% end %>
<% end %>

<% if @user.watchlist %>
  <%= link_to user_watchlists_path(@user), class: "button" do %>
    <i class="fas fa-video"></i>
    <span><%= pluralize(@user.watchlist.movies.count, 'movie') %> </span>
  <% end %>
<% end %>

<br><br>

<p><%= @user.render_bio if @user.bio %></p><br>
<div><%= render 'follow_button' %></div>
</div><br>

app/views/users/_recent_reviews.html.erb
<h2>recent reviews.</h2>

<div class="dash-review-container">
<% @user.reviews.last(5).reverse.each do |review| %>
  <div class="review">
    <div class="dash-image">
      <%= link_to image_tag(review.movie.poster), review_path(review) %>
    </div>
    <h2><%= link_to review.movie.titleyear, movie_path(review.movie) %></h2>
    <span><%= review.render_content %></span>
  </div>
<% end %>
<%= link_to user_reviews_path(@user), class: "button" do %>
  <span>more</span>
  <i class="fas fa-chevron-circle-right"></i>
<% end %>
</div>

app/views/users/_watchlist.html.erb
<% if @user.watchlist && @user.watchlist.movies.present? %>
  <h2>Movies in <%= @user.username %>'s watchlist.</h2>
  <div class="movie-list row">
    <% @user.watchlist.movies.sample(5).each do |movie| %>
      <div class="result-cards">
        <%= link_to image_tag(movie.poster), movie_path(movie), data_value: movie.titleyear %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/dashboard.html.erb
<section class="dashboard">

<% if @popular.present? %>
  <h2>popular this week.</h2>
  <div class="movie-list row">
    <% @popular.first(5).each do |movie| %>
      <div class="result-cards">
        <%= link_to image_tag(movie.poster), movie_path(movie), data_value: movie.titleyear %>
      </div>
    <% end %>
  </div>
<% end %>

<h2>reviews from people you follow.</h2>
<%if @following.empty? %> <h3 class="accent">you're not following anybody yet.</h3> <% end %>

<div class="dash-review-container">
  <% all_follow_reviews(@following, 25).each do |review|%>
    <small class="dash-date"><%=review.render_date %> &nbsp<i class="far fa-calendar accent"></i></small>
    <div class="review">
      <div class="dash-image">
        <%= link_to image_tag(review.movie.poster), review_path(review) %>
      </div>
      <%= link_to review.user.username, user_path(review.user), class: "username" %>
      <h2><%= link_to review.movie.titleyear, movie_path(review.movie) %></h2>
      <span><%= review.render_content %></span><br>
    </div>
  <% end %>
</div>
</section>

app/views/users/followers.html.erb
<%= render 'followers' %>

app/views/users/following.html.erb
<%= render 'following' %>

app/views/users/show.html.erb
<div class="profile-container">

<%= render 'profile_info' %>
<%= render 'watchlist' %>

<% if @user.reviews.present? %>
  <%= render "recent_reviews" %>
<% end %>

</div>