config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: "registrations" }

  resources :movies, only: [:new, :index, :show, :create] do
    resources :reviews, only: [:index, :create, :new]
  end
  resources :users, only: :show, path: 'profile' do
    resources :reviews, only: [:index]
    resources :watchlists, only: [:index]
    member do
      get :follow
      get :unfollow
      get :followers
      get :following
    end
  end

  resources :reviews, except: [:new, :index]
  resources :tags, only: [:show]
  resources :watchlists, only: [:create, :update, :index]

  get '/search', to: 'movies#new'
  get '/dashboard', to: 'users#dashboard'

  root 'welcome#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action do
    set_movie_list(params[:search])
  end

  def set_movie_list(string)
    result = HTTParty.get("http://www.omdbapi.com/?s=#{string}&apikey=2cedcff3&")
    @movie_list = []
    if !result['Error'] && !result.nil?
      @movie_list = result['Search'].compact.map do |m|
        poster = m['Poster'] == 'N/A' ? 'https://66.media.tumblr.com/5a186c216ce45dbc68730be8ced57a06/29fe15eaade870e6-a7/s400x600/1c5884a55da0a8d151061ab122fbd715e201f7b9.png' : m['Poster']
        Movie.new(
          title: m['Title'],
          year: m['Year'],
          poster: poster,
          imdbid: m['imdbID']
        )
      end
    elsif result['Error'] == "Movie not found!"
      flash[:alert] = "no results"
    end
  end

  def set_movie(string)
    result = HTTParty.get("http://www.omdbapi.com/?i=#{string}&apikey=2cedcff3&").compact
    dir = result['Director'] == 'N/A' ? result['Writer'] : result['Director']
    poster = result['Poster'] == 'N/A' ? 'https://66.media.tumblr.com/5a186c216ce45dbc68730be8ced57a06/29fe15eaade870e6-a7/s400x600/1c5884a55da0a8d151061ab122fbd715e201f7b9.png' : result['Poster']
    @movie = Movie.new(
      title: result['Title'],
      year: result['Year'],
      genre: result['Genre'],
      director: dir,
      poster: poster,
      plot: result['Plot'],
      imdbid: result['imdbID']
    )
  end

  def find_or_create_movie(query)
    if @movie = Movie.find_by(imdbid: query)
      redirect_to @movie
    elsif set_movie(query).save
      redirect_to @movie
    end
  end

  def update_or_create_watchlist
    if current_user.watchlist.nil?
      @watchlist = Watchlist.new
      current_user.watchlist = @watchlist
      @watchlist.movies << @movie
      if @watchlist.save
        flash[:notice] = "movie added to watchlist"
        return redirect_to movie_path(@movie)
      end
    elsif !current_user.watchlist.movies.include?(@movie)
      current_user.watchlist.movies << @movie
      flash[:notice] = "movie added to watchlist"
      return redirect_to movie_path(@movie)
    else
      redirect_to movie_path(@movie)
    end
  end

  protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:bio, :username, :tagline])

   devise_parameter_sanitizer.permit(:account_update, keys: [:bio, :username, :tagline])
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_blocker.html.erb
<div id="blocker"></div>

app/views/application/_flash.html.erb
  <% if flash[:notice] %>
    <p class="flash notice "><%= flash[:notice] %></p>
  <% elsif flash[:alert] %>
    <p class="flash alert"><%= flash[:alert] %></p>
  <% end %>

app/views/application/_home_button.html.erb
<%= button_to root_path, method: :get, class: "button" do %>
  <i class="fas fa-stream"></i>
<%end%>
<%= button_to user_path(current_user), method: :get, class: "button" do %>
  <i class="far fa-meh-blank"></i>
<%end%>

app/views/application/_logo.html.erb
<div class="logo">
  <%= link_to root_path do %>
  FILM<span class="accent">r</span>.
  <% end %>
</div>

app/views/application/_logout_button.html.erb
<% if user_signed_in? %>
  <%= button_to "log out", destroy_user_session_path, method: :delete, class: "session-button delete-button button" %>
<% end %>

app/views/application/_main_menu.html.erb
<div id="menu">
    <div class="menu-list">
      <h1><%= link_to current_user.username, user_path(current_user), class: "username" %></h1>

      <%= link_to watchlists_path do %>
      <i class="fas fa-th-large"></i>
      <span>movies</span>
      <% end %>

      <%= link_to dashboard_path do %>
      <i class="fas fa-stream"></i>
      <span>dashboard</span>
      <% end %>

      <%= link_to edit_user_registration_path do %>
      <i class="fas fa-user-edit"></i>
      <span>manage profile</span>
      <% end %>

      <%= link_to destroy_user_session_path, method: :delete do %>
      <%= fa_icon "times-circle" %>
      <span>logout</span>
      <% end %>

    </div>
</div>

app/views/application/_menu_button.html.erb
<div id="btn">
  <div class="line"></div>
</div>

app/views/application/_movie_data.html.erb
  <h2><%= movie.titleyear %></h2><br>
  <%= link_to image_tag(movie.poster), movie_path(movie) %>
  <h3><%= movie.director %></h3><br>
  <% movie.genres.each do |genre| %>
    <span class="genre"><%= genre.downcase %></span>
  <% end %>
  <hr><br>
  <p><%= movie.plot %></p>

app/views/application/_movie_list.html.erb
<br><h2>search results.</h2>
<%= form_with model: @movie, class: "movie-list", id: "movie-list" do |f| %>
<div class="row">
  <%= f.collection_radio_buttons(:imdbid, @movie_list, :imdbid, :render_poster, id: :titleyear) do |b| %>
    <%= b.radio_button(value: b.object.titleyear) + b.label(class: "result-cards", data_value: b.object.titleyear) %>
  <% end %>
</div>
<% end %>

app/views/application/_search_form.html.erb
<div class="search_form">
<%= form_tag  do %>
  <%= text_field_tag('search', nil, placeholder: 'search for a movie') %>
  <%= hidden_field_tag :_method, :get %>

  <%= button_tag type: 'submit', class: "button" do %>
    <i class="fas fa-search"></i>
  <% end %>
<% end %>
<% if params[:search] %>
<%= render 'search_results' %>
<% end %>
</div>

app/views/application/_search_results.html.erb
<div class="search-container">
<% if @movie_list.present? %>
  <h3>search results.</h3>
  <%= form_with url: movies_path, class: "search-results", id: "movie-list", local: true do |f| %>
  <div class="row">
    <%= f.collection_radio_buttons(:imdbid, @movie_list, :imdbid, :render_poster, id: :titleyear) do |b| %>
      <%= b.radio_button(value: b.object.titleyear) + b.label(class: "result-cards", data_value: b.object.titleyear) %>
    <% end %>
  </div>
  <% end %>
  <div class="close-button button delete-button"><i class="fas fa-window-close"></i></div>
<% end %>
</div>