config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: "registrations" }

  resources :movies, only: [:new, :index, :show, :create] do
    resources :reviews, only: [:index, :create, :new]
  end
  resources :users, only: :show, path: 'profile' do
    resources :reviews, only: [:index]
    resources :watchlists, only: [:index]
    member do
      get :follow
      get :unfollow
      get :followers
      get :following
    end
  end

  resources :reviews, except: [:new, :index]
  resources :tags, only: [:show]
  resources :watchlists, only: [:create, :update, :index]

  get '/search', to: 'movies#new'
  get '/dashboard', to: 'users#dashboard'

  root 'welcome#index'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def index
    @user = User.find_by(id: params[:user_id])
    @reviews = @user.reviews
  end

  def new
    @movie = Movie.find_by(id: params[:movie_id])
    @review = Review.new(movie_id: params[:movie_id])
  end

  def create
    @movie = Movie.find_by(id: params[:review][:movie_id])
    @review = Review.new(review_params)
    if @review.save
      update_or_create_watchlist
    else
      render :new
    end
  end

  def show
  end

  def edit
    if !@review.owns? current_user
      redirect_to root_path, alert: "you don't have permission to do that."
    end
  end

  def update
    @review.update(review_params)
    redirect_to @review, notice: "finished polishing up your review of #{@review.movie.title}"
  end

  def destroy
    @review.destroy
    redirect_to user_path(current_user), alert: "your review of #{@review.movie.title} is gonve forever."
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end


  def review_params
    params.require(:review).permit(:content, :date, :tag_name, :movie_id, :user_id)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/edit.html.erb
<section class="row">
  <section class="column col-left">
    <div class="movie-data">
      <%= render partial: 'movie_data', locals: {movie: @review.movie} %>
    </div>
  </section>

  <div class="column dash-review-container edit-form">
    <h2>edit your review.</h2>
    <%= form_with model: @review do |f| %>
      <%= f.text_area :content %>
      <%= f.text_field :tag_name %>

      <%= f.submit class: "button" %>
    <% end %>
  </div>

</section>

app/views/reviews/index.html.erb
<div class="dashboard">
<h1>all reviews by <%= @user.username %>.</h1>
<div class="dash-review-container">
<% @reviews.reverse.each do |review| %>
  <div class="review">
    <div class="dash-image"><%= link_to image_tag(review.movie.poster), review_path(review) %>
    </div>
    <h2><%= link_to review.movie.titleyear, movie_path(review.movie) %></h2>
    <span><%= review.render_content %></span>
  </div>
<% end %>
</div>
</div>

app/views/reviews/new.html.erb
<section class="row">
  <div class="column col-left">
    <div class="movie-data">
      <%= render partial: 'movie_data', locals: {movie: @movie} %>
    </div>
  </div>

  <div class="column col-right">

    <%= form_with model: @review, local: true do |f| %>

    <% if @review.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@review.errors.count, "error") %>
        prohibited this review from being saved:
      </h3>
        <% @review.errors.full_messages.each do |msg| %>
        <p class="red"><%= msg %></p>
        <% end %>
    </div>
    <% end %>

      <%= f.hidden_field :movie_id %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :date, value: Time.now %>
      <%= f.text_area :content, placeholder: "write a review" %><br>

      <%= f.text_field :tag_name, placeholder: "comma separated tags" %>

      <%= button_tag type: 'submit', class: "button" do %>
        <%= fa_icon "chevron-right" %>
      <% end %>
    <% end %>
  </div>

</section>

app/views/reviews/show.html.erb
<section class="row">
  <div class="column col-left">
  <div class="movie-data">
    <%= render partial: 'movie_data', locals: {movie: @review.movie} %>
    <br>
    <div class="row">
      <% if @review.owns? current_user %>
        <%= button_to review_path(@review), method: :delete, class: "button delete-button" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
        <%= button_to edit_review_path(@review), method: :get, class: "button data-button" do %>
          <i class="fas fa-edit"></i>
        <%end%>
      <% end %>
      <%= render 'home_button' %>
    </div>
    </div>
  </div>

  <div class="column dash-review-container">
    <h3>review by: </h3>
    <span><%= link_to @review.user.username, user_path(@review.user), class: "username" %></span><br>
    <p class="review review-show"><%= @review.render_content %></p>
    <p><i class="far fa-calendar"></i> <%= @review.render_date %></p><br>
    <% if @review.tags.present? %>
      <span>
        <% @review.tags.each do |tag| %>
          <%= link_to tag_path(tag), class: "tag" do %>
          <i class="fas fa-circle fa-xs"></i>
          <span><%= tag.name %></span>
          <% end %>
        <% end %>
      </span>
    <% end %>
  <br><br>
  </div>

</section>